export const TASK_POOLS = {
  '6-8': {
    Athletic: [
      { id: 'sit_unsupported', text: 'Sit unsupported for 1 minute' },
      { id: 'tummy_reach', text: 'Reach for toys while on tummy' },
      { id: 'roll_both', text: 'Roll from back to tummy and tummy to back' },
      { id: 'supported_stand', text: 'Bounce while supported in a standing position' },
      { id: 'airplane_pose', text: 'Lift arms and legs in "airplane" pose on tummy' },
      { id: 'pivot_tummy', text: 'Pivot in a circle while on tummy' },
      { id: 'sit_reach_fwd', text: 'Sit and reach forward for a toy without falling' },
      { id: 'push_up_tummy', text: 'Push chest up with straight arms during tummy time' },
      { id: 'feet_to_mouth', text: 'Bring feet to mouth while lying on back' },
      { id: 'assisted_roll', text: 'Follow a rolling ball by rolling their body' },
      { id: 'sit_reach_side', text: 'Sit and reach to the side for a toy' },
      { id: 'wiggle_fwd', text: 'Wiggle or scoot forward slightly on tummy' },
      { id: 'stand_holds_hands', text: 'Bear weight on legs when held by hands' },
      { id: 'sit_play', text: 'Sit and play with a toy using both hands' },
      { id: 'rock_hands_knees', text: 'Get on hands and knees and rock back and forth' },
      { id: 'roll_away', text: 'Roll away from a diaper change (classic!)' },
      { id: 'tummy_kick', text: 'Kick legs alternatingly while on tummy' },
      { id: 'sit_recover', text: 'Catch themselves with hands when falling from sitting' },
      { id: 'back_arch', text: 'Arch back to look upside down when on back' },
      { id: 'tummy_endurance', text: 'Stay in tummy time for 5+ minutes comfortably' }
    ],
    Cognitive: [
      { id: 'bang_toys', text: 'Bang two toys together' },
      { id: 'find_hidden', text: 'Find partially hidden object' },
      { id: 'mirror_look', text: 'Look at themselves in a mirror' },
      { id: 'drop_look', text: 'Drop a toy and look down to see where it fell' },
      { id: 'cause_effect', text: 'Play with a cause-and-effect button toy' },
      { id: 'explore_mouth', text: 'Explore a new textured object with their mouth' },
      { id: 'shake_rattle', text: 'Shake a rattle intentionally to make noise' },
      { id: 'track_fast', text: 'Visually track a fast-moving object' },
      { id: 'respond_no', text: 'Pause briefly when told "no"' },
      { id: 'inspect_hands', text: 'Examine their own hands and fingers closely' },
      { id: 'pat_picture', text: 'Pat a high-contrast picture in a board book' },
      { id: 'turn_head_name', text: 'Turn head immediately when their name is called' },
      { id: 'anticipate_game', text: 'Show excitement anticipating a peek-a-boo reveal' },
      { id: 'different_feels', text: 'Discriminate between a hard block and a soft plush' },
      { id: 'listen_story', text: 'Listen quietly for 1 minute while reading a book' },
      { id: 'object_constancy', text: 'Realize a cup is a cup even when upside down' },
      { id: 'pull_string', text: 'Pull a string to get a toy attached to it' },
      { id: 'drop_wait', text: 'Drop food from high chair and wait to hear it land' },
      { id: 'study_face', text: 'Intently study a caregiver\'s face' },
      { id: 'notice_new', text: 'Notice a new object placed in a familiar room' }
    ],
    Social: [
      { id: 'respond_name', text: 'Respond to own name' },
      { id: 'smile_reflection', text: 'Smile at reflection' },
      { id: 'reach_pickup', text: 'Reach to be picked up' },
      { id: 'babble_back', text: 'Babble back and forth like a conversation' },
      { id: 'laugh_loud', text: 'Laugh out loud at a silly noise or face' },
      { id: 'stranger_shy', text: 'Show shyness or caution around strangers' },
      { id: 'mimic_face', text: 'Mimic a facial expression (e.g., wide mouth)' },
      { id: 'vocalize_attn', text: 'Make noises specifically to get your attention' },
      { id: 'stop_cry_voice', text: 'Stop crying when hearing a caregiver\'s voice' },
      { id: 'play_food', text: 'Interact playfully during mealtime' },
      { id: 'cling_parent', text: 'Cling to a parent in a new environment' },
      { id: 'wave_arms_joy', text: 'Wave arms excitedly when a favorite person appears' },
      { id: 'recognize_tone', text: 'Change expression based on your tone of voice' },
      { id: 'comfort_object', text: 'Show attachment to a specific blanket or toy' },
      { id: 'initiate_play', text: 'Try to initiate a game like peek-a-boo' },
      { id: 'babble_strings', text: 'String consonant-vowel sounds (ba-ba-ba)' },
      { id: 'eye_contact_feed', text: 'Maintain eye contact during feeding' },
      { id: 'express_disgust', text: 'Show clear distaste for a sour/bitter food' },
      { id: 'protest_leave', text: 'Vocalize protest if you leave the room' },
      { id: 'enjoy_tickles', text: 'Anticipate and giggle before being tickled' }
    ],
    FineMotor: [
      { id: 'pass_toy', text: 'Pass toy from one hand to other' },
      { id: 'rake_grasp', text: 'Rake small objects closer with fingers' },
      { id: 'hold_two', text: 'Hold two items, one in each hand' },
      { id: 'hold_bottle', text: 'Help hold their own bottle while feeding' },
      { id: 'finger_feed', text: 'Attempt to self-feed a melt or puff' },
      { id: 'early_pincer', text: 'Use thumb and side of index finger to grab' },
      { id: 'pull_hair', text: 'Grab and pull hair or glasses (firm grip!)' },
      { id: 'scratch_surface', text: 'Scratch fingers on a textured surface' },
      { id: 'squeeze_toy', text: 'Squeeze a soft squeaky toy' },
      { id: 'bang_table', text: 'Bang an object repeatedly on a table' },
      { id: 'drop_voluntary', text: 'Let go of a toy voluntarily (not just dropping)' },
      { id: 'pull_off_sock', text: 'Pull off their own sock' },
      { id: 'grab_spoon', text: 'Grab the spoon while you are feeding them' },
      { id: 'turn_board_page', text: 'Crudely try to turn a thick board book page' },
      { id: 'explore_holes', text: 'Poke fingers into a toy with holes (Oball)' },
      { id: 'crumple_paper', text: 'Crumple a piece of tissue paper' },
      { id: 'pull_wipe', text: 'Pull a single wipe out of the container' },
      { id: 'pat_dog', text: 'Gently pat a pet (with guidance)' },
      { id: 'reach_cross', text: 'Reach across their body with one hand' },
      { id: 'point_whole', text: 'Point at an object with their whole hand/arm' }
    ]
  },
  '9-11': {
    Athletic: [
      { id: 'crawl', text: 'Crawl or army crawl' },
      { id: 'pull_stand', text: 'Pull up to stand' },
      { id: 'cruise', text: 'Cruise along furniture' },
      { id: 'stand_sec', text: 'Stand independently for 2-3 seconds' },
      { id: 'sit_from_stand', text: 'Lower from standing to sitting safely' },
      { id: 'climb_pillow', text: 'Climb over a large floor pillow' },
      { id: 'crawl_stairs', text: 'Crawl up one step of stairs' },
      { id: 'kneel_play', text: 'Kneel upright without hand support to play' },
      { id: 'squat_hold', text: 'Squat down while holding on to furniture' },
      { id: 'walk_hands_held', text: 'Walk forward while both hands are held' },
      { id: 'crawl_tunnel', text: 'Crawl through a play tunnel or box' },
      { id: 'pivot_seated', text: 'Twist around while seated to grab a toy behind' },
      { id: 'push_walker', text: 'Push a sturdy push-walker toy a few steps' },
      { id: 'climb_lap', text: 'Crawl and climb up into a caregiver\'s lap' },
      { id: 'balance_wobble', text: 'Stand and play on a slightly wobbly surface (cushion)' },
      { id: 'trans_crawl_sit', text: 'Move seamlessly from crawling to sitting' },
      { id: 'pull_stand_smooth', text: 'Pull to stand using a smooth motion (less pulling, more legs)' },
      { id: 'cruise_corners', text: 'Cruise around an outside corner of the couch' },
      { id: 'stand_one_hand', text: 'Stand while holding on with only one hand' },
      { id: 'step_over_toy', text: 'Step over a small toy while cruising' }
    ],
    Cognitive: [
      { id: 'drop_toy_look', text: 'Drop toys intentionally to watch them fall' },
      { id: 'peek_a_boo', text: 'Play peek-a-boo' },
      { id: 'find_hidden_full', text: 'Find fully hidden object' },
      { id: 'understand_no', text: 'Stop action when hearing a stern "no"' },
      { id: 'copy_sounds', text: 'Imitate animal or vehicle sounds' },
      { id: 'point_picture', text: 'Point to a familiar picture in a book' },
      { id: 'use_cup_correct', text: 'Pretend to drink from an empty cup' },
      { id: 'nesting_cups', text: 'Try to fit one nesting cup into another' },
      { id: 'find_different_room', text: 'Look toward the door when someone leaves' },
      { id: 'knows_name', text: 'Clearly responds to their name consistently' },
      { id: 'follow_point', text: 'Look where you are pointing' },
      { id: 'object_permanence', text: 'Search for a toy hidden under 2 layers' },
      { id: 'wave_bye_prompted', text: 'Wave bye-bye when prompted verbally' },
      { id: 'sort_basic', text: 'Take objects out of a container and put them back' },
      { id: 'recognize_words', text: 'Show recognition of words like "shoe" or "ball"' },
      { id: 'explore_functions', text: 'Press buttons, spin dials, slide switches' },
      { id: 'anticipate_routine', text: 'Show preparing action (lift arms) for a shirt' },
      { id: 'find_missing', text: 'Look for the ball that rolled under the couch' },
      { id: 'basic_problem_solve', text: 'Move an obstacle to get a desired toy' },
      { id: 'listen_music', text: 'Bounce or sway to music' }
    ],
    Social: [
      { id: 'wave_bye', text: 'Practice waving "Bye-bye"' },
      { id: 'shake_no', text: 'Shake head "no"' },
      { id: 'point', text: 'Point to things of interest' },
      { id: 'stranger_fear', text: 'Show clear preference/fear with strangers' },
      { id: 'offer_toy', text: 'Hold out a toy to show you (but not release it)' },
      { id: 'play_pat_a_cake', text: 'Clap hands for pat-a-cake' },
      { id: 'seek_approval', text: 'Look at you for a reaction after doing something' },
      { id: 'mimic_chores', text: '"Help" by holding a wipe or spoon' },
      { id: 'separation_anxiety', text: 'Cry when parent leaves the room' },
      { id: 'test_boundaries', text: 'Do something prohibited while holding eye contact' },
      { id: 'share_food', text: 'Try to feed you a piece of their food' },
      { id: 'give_kisses', text: 'Give open-mouth kisses' },
      { id: 'raise_arms', text: 'Raise arms to signal "pick me up"' },
      { id: 'enjoy_audience', text: 'Repeat an action that made everyone laugh' },
      { id: 'comfort_others', text: 'Pat another crying baby (early empathy)' },
      { id: 'vocal_turns', text: 'Take turns making sounds in a "conversation"' },
      { id: 'recognize_mirror', text: 'Recognize themselves vs another baby in mirror' },
      { id: 'favorite_person', text: 'Show clear joy when a specific person arrives' },
      { id: 'play_chase', text: 'Crawl away laughing when chased' },
      { id: 'follow_gaze', text: 'Look at what another person is looking at' }
    ],
    FineMotor: [
      { id: 'pincer_grasp', text: 'Pick up small item (pincer grasp)' },
      { id: 'put_in_container', text: 'Put objects into a container' },
      { id: 'poke', text: 'Poke with index finger' },
      { id: 'turn_book_pages', text: 'Turn multiple thick board pages at once' },
      { id: 'feed_self_puffs', text: 'Consistently self-feed small finger foods' },
      { id: 'bang_blocks', text: 'Bang two wooden blocks together' },
      { id: 'drop_in_cup', text: 'Drop a small toy into a cup' },
      { id: 'take_out_peg', text: 'Remove a loose peg from a hole' },
      { id: 'hold_crayon', text: 'Hold a crayon in a fist grip' },
      { id: 'push_car', text: 'Push a toy car back and forth' },
      { id: 'stack_attempt', text: 'Try to stack one block on top of another' },
      { id: 'rip_paper', text: 'Tear a piece of paper or magazine page' },
      { id: 'squeeze_pouch', text: 'Squeeze a food pouch (maybe making a mess!)' },
      { id: 'explore_velcro', text: 'Pull apart velcro straps on shoes' },
      { id: 'pull_cabinet', text: 'Pull open a lightweight drawer or door' },
      { id: 'point_index', text: 'Isolate index finger to point or press a button' },
      { id: 'uncover_toy', text: 'Pull a cloth off a hidden toy' },
      { id: 'hold_spoon_feed', text: 'Hold a spoon, though spilling most of it' },
      { id: 'pick_up_string', text: 'Pick up a piece of string or yarn' },
      { id: 'transfer_smooth', text: 'Smoothly transfer a toy hand-to-hand without looking' }
    ]
  },
  '12-14': {
    Athletic: [
      { id: 'stand_alone', text: 'Stand alone for a few seconds' },
      { id: 'take_steps', text: 'Take a few independent steps' },
      { id: 'push_toy', text: 'Push-toy parade (lawnmower or cart)' },
      { id: 'walk_uneven', text: 'Walk on thick carpet or grass' },
      { id: 'climb_couch', text: 'Attempt to climb onto the couch' },
      { id: 'squat_stand', text: 'Squat to pick up a toy and stand back up' },
      { id: 'walk_carry', text: 'Walk while carrying a medium-sized toy' },
      { id: 'stair_crawl_up', text: 'Crawl up a flight of padded stairs (supervised)' },
      { id: 'stair_slide_down', text: 'Slide down stairs backward on tummy' },
      { id: 'dance_bounce', text: 'Bounce or bend knees to dance to music' },
      { id: 'ride_toy', text: 'Sit on a ride-on toy and push with feet' },
      { id: 'fast_crawl', text: 'Crawl very rapidly to get somewhere quickly' },
      { id: 'recover_balance', text: 'Catch balance when tripped slightly' },
      { id: 'walk_fast', text: 'Walk at a fast, almost-running pace' },
      { id: 'step_back', text: 'Take a step sideways or backward' },
      { id: 'climb_chair', text: 'Climb onto a low child-sized chair' },
      { id: 'throw_under', text: 'Throw a ball underhand (uncoordinated)' },
      { id: 'kick_attempt', text: 'Try to kick a large ball (might miss)' },
      { id: 'pull_toy_string', text: 'Walk while pulling a toy on a string' },
      { id: 'spin_circles', text: 'Try to spin in circles' }
    ],
    Cognitive: [
      { id: 'follow_one_step', text: 'Follow 1-step command with gesture' },
      { id: 'use_correctly', text: 'Use objects correctly (e.g., cup, brush)' },
      { id: 'look_named', text: 'Look at named picture in a book' },
      { id: 'first_word', text: 'Say a clear first word (other than mama/dada)' },
      { id: 'point_body_part', text: 'Point to one body part when asked' },
      { id: 'find_match', text: 'Match an object to its picture' },
      { id: 'imitate_sounds', text: 'Imitate animal sounds (moo, baa)' },
      { id: 'stack_rings', text: 'Place rings on a stacking post (any order)' },
      { id: 'shape_sorter_1', text: 'Put round block in round hole (with help)' },
      { id: 'hidden_search', text: 'Search multiple places for a hidden toy' },
      { id: 'bring_shoe', text: 'Bring shoes when it is time to go out' },
      { id: 'pretend_phone', text: 'Put a phone (or block) to ear and babble' },
      { id: 'knows_routines', text: 'Anticipate bath time when water runs' },
      { id: 'point_to_want', text: 'Point exactly at what they want out of reach' },
      { id: 'recognize_name_others', text: 'Look at sibling/pet when their name is said' },
      { id: 'use_sign', text: 'Use an ASL sign like "more" or "all done"' },
      { id: 'scribble_meaning', text: 'Scribble and "tell" you what it is via babbling' },
      { id: 'empty_fill', text: 'Obsessively empty and fill a container' },
      { id: 'explore_nature', text: 'Examine a leaf or bug outside closely' },
      { id: 'try_keys', text: 'Try to put toy keys into a lock shape' }
    ],
    Social: [
      { id: 'hand_book', text: 'Hand a book when they want a story' },
      { id: 'play_pat_a_cake', text: 'Play pat-a-cake with another person' },
      { id: 'initiate_game', text: 'Initiate a favorite game (bring blanket for peekaboo)' },
      { id: 'show_empathy', text: 'Look sad if they see someone crying' },
      { id: 'tantrum_start', text: 'Throw a minor tantrum when frustrated' },
      { id: 'hug_stuffed', text: 'Hug or kiss a favorite stuffed animal' },
      { id: 'greeting', text: 'Wave or say "hi" unprompted when someone enters' },
      { id: 'show_pride', text: 'Clap for themselves when they succeed' },
      { id: 'test_no', text: 'Say "no" and shake head' },
      { id: 'parallel_start', text: 'Watch other kids intensely at the park' },
      { id: 'share_bite', text: 'Offer a bite of their snack to a parent' },
      { id: 'comfort_seek', text: 'Run to parent for comfort when hurt' },
      { id: 'joint_attention', text: 'Point to a bird, make sure you see it too' },
      { id: 'help_dress', text: 'Push arm through sleeve when dressing' },
      { id: 'imitate_chores', text: 'Try to sweep or wipe the table' },
      { id: 'understand_praise', text: 'Smile widely when praised ("good job!")' },
      { id: 'play_ball', text: 'Roll a ball back and forth with a partner' },
      { id: 'shy_new', text: 'Hide behind legs in a new environment' },
      { id: 'laugh_slapstick', text: 'Laugh if an adult clumsily drops something' },
      { id: 'greet_pets', text: 'Show excitement/greet family pet in the morning' }
    ],
    FineMotor: [
      { id: 'take_out', text: 'Take objects out of a container' },
      { id: 'turn_pages_thick', text: 'Turn thick board book pages (1 at a time)' },
      { id: 'mark_paper', text: 'Make marks on paper with crayon' },
      { id: 'stack_three', text: 'Stack 2-3 blocks in a tower' },
      { id: 'drink_cup', text: 'Drink from open cup (creates a mess)' },
      { id: 'use_spoon', text: 'Feed self with a spoon (food often falls)' },
      { id: 'peg_board', text: 'Put large pegs into a pegboard' },
      { id: 'pop_bubbles', text: 'Poke at floating bubbles to pop them' },
      { id: 'turn_knob', text: 'Turn a large knob on a toy' },
      { id: 'pull_zipper', text: 'Pull a large zipper tag down' },
      { id: 'take_off_hat', text: 'Pull off their own hat or headband' },
      { id: 'drop_coin_slot', text: 'Try to drop a coin into a large slot' },
      { id: 'squeeze_sponge', text: 'Squeeze a wet sponge in the bath' },
      { id: 'peel_sticker', text: 'Try to peel a sticker off their shirt' },
      { id: 'hold_two_small', text: 'Hold two small items in one hand' },
      { id: 'push_buttons', text: 'Push buttons on the TV remote' },
      { id: 'finger_paint', text: 'Smear finger paint or yogurt on a tray' },
      { id: 'open_box', text: 'Lift the lid off a small box' },
      { id: 'turn_steering', text: 'Turn a toy steering wheel' },
      { id: 'pincer_tiny', text: 'Pick up a tiny crumb using precise pincer grasp' }
    ]
  },
  '15-17': {
    Athletic: [
      { id: 'walk_well', text: 'Walk well independently without falling often' },
      { id: 'stair_climb_assist', text: 'Climb stairs with assistance (holding hand)' },
      { id: 'squat_play', text: 'Squat to play with a toy on the floor, then stand' },
      { id: 'walk_backwards', text: 'Take a few steps backwards' },
      { id: 'run_stiffness', text: 'Attempt to run (looks like a stiff, fast walk)' },
      { id: 'kick_ball', text: 'Kick a large stationary ball' },
      { id: 'climb_slide', text: 'Climb up the steps of a small slide' },
      { id: 'throw_over', text: 'Throw a ball overhand' },
      { id: 'step_over', text: 'Step over a low obstacle (like a broom stick)' },
      { id: 'jump_attempt', text: 'Try to jump (mostly bobbing up and down)' },
      { id: 'carry_large', text: 'Carry a large, awkward toy across the room' },
      { id: 'ride_push', text: 'Propel a ride-on toy with both feet' },
      { id: 'dance_spin', text: 'Spin around in circles to music until dizzy' },
      { id: 'walk_uneven_well', text: 'Walk smoothly on grass or mulch' },
      { id: 'stair_down_creep', text: 'Creep down stairs backwards safely' },
      { id: 'balance_one_sec', text: 'Balance on one foot while holding a hand' },
      { id: 'climb_out_crib', text: 'Attempt to climb out of crib or playpen' },
      { id: 'push_stroller', text: 'Push their own empty stroller' },
      { id: 'walk_sideways', text: 'Side-step along a wall' },
      { id: 'chase_game', text: 'Play a game of chase in the yard' }
    ],
    Cognitive: [
      { id: 'point_body_more', text: 'Point to 2-3 body parts when asked' },
      { id: 'srt_basic_shapes', text: 'Basic sorting (e.g. circle in circle hole)' },
      { id: 'imitate_chores_more', text: '"Help" with chores (wiping, sweeping)' },
      { id: 'five_words', text: 'Use 5-10 words consistently and correctly' },
      { id: 'two_step_game', text: 'Follow 2-step command (Get ball, give to dad)' },
      { id: 'name_picture', text: 'Name a familiar object in a picture book' },
      { id: 'know_uses_cup', text: 'Know a cup is for drinking, hat for head' },
      { id: 'animal_noises', text: 'Make 3 different animal noises' },
      { id: 'match_pairs', text: 'Find the other matching shoe' },
      { id: 'point_truck', text: 'Point to a truck or dog outside when asked' },
      { id: 'pretend_feed', text: 'Pretend to feed a doll or stuffed animal' },
      { id: 'solve_puzzle', text: 'Complete a simple 2-3 piece inset puzzle' },
      { id: 'recognize_self_photo', text: 'Recognize themselves in a photo' },
      { id: 'understand_all_done', text: 'Understand "all done" and clean up' },
      { id: 'bring_diaper', text: 'Bring a clean diaper when asked' },
      { id: 'sort_colors', text: 'Try to group items by color (fails often)' },
      { id: 'stack_size', text: 'Stack nesting cups in roughly the right size order' },
      { id: 'concept_up', text: 'Understand "up" vs "down"' },
      { id: 'hum_tune', text: 'Hum along to a familiar nursery rhyme' },
      { id: 'find_hidden_complex', text: 'Remember where a toy was hidden yesterday' }
    ],
    Social: [
      { id: 'show_affection', text: 'Show affection (hug/kiss) unprompted' },
      { id: 'bring_toy_show', text: 'Bring toy just to show you (joint attention)' },
      { id: 'point_ask_more', text: 'Point to ask for something specific' },
      { id: 'say_no', text: 'Say "no" frequently to assert independence' },
      { id: 'play_near_kids', text: 'Play happily near other children (parallel play)' },
      { id: 'show_jealousy', text: 'Show jealousy if parent holds another baby' },
      { id: 'comfort_doll', text: 'Pat a doll\'s back to comfort it' },
      { id: 'hand_over_toy', text: 'Hand over a toy to another child (sometimes!)' },
      { id: 'seek_help', text: 'Hand you a closed jar to ask for help opening it' },
      { id: 'laugh_silly', text: 'Laugh at incongruous things (shoe on head)' },
      { id: 'greet_fam', text: 'Run to greet a family member returning home' },
      { id: 'wave_hi_bye', text: 'Wave "Hi" and "Bye" consistently in context' },
      { id: 'tantrum_peak', text: 'Experience intense frustration tantrums' },
      { id: 'imitate_phone', text: 'Walk around talking into a pretend phone' },
      { id: 'share_snack', text: 'Offer a piece of their snack to a sibling' },
      { id: 'hide_seek', text: 'Play a simple game of hide and seek' },
      { id: 'help_unpack', text: 'Help pull items out of grocery bags' },
      { id: 'show_wounds', text: 'Point to a scratch or boo-boo for sympathy' },
      { id: 'refuse_food', text: 'Push plate away when full' },
      { id: 'clap_success', text: 'Clap when they or someone else does something good' }
    ],
    FineMotor: [
      { id: 'stack_four_more', text: 'Stack 4 blocks in a tower' },
      { id: 'feed_self_fingers', text: 'Feed self well with fingers quickly' },
      { id: 'cup_drink_spill', text: 'Drink from open cup with some spills' },
      { id: 'scribble_spontaneous', text: 'Scribble spontaneously with a crayon' },
      { id: 'turn_knobs', text: 'Turn round doorknobs' },
      { id: 'use_fork_basic', text: 'Stab soft food with a toddler fork' },
      { id: 'take_off_socks_shoes', text: 'Take off own socks and shoes' },
      { id: 'zipper_down_pull', text: 'Unzip a zipper completely' },
      { id: 'put_in_shapes_circle', text: 'Put shapes into a shape sorter (circle is easy)' },
      { id: 'string_bead_try', text: 'Try to thread a large bead on a string' },
      { id: 'turn_book_thin_few', text: 'Attempt to turn paper pages (turns 2-3)' },
      { id: 'open_drawer_pull', text: 'Open and close a drawer' },
      { id: 'twist_lid_jar', text: 'Unscrew a loose lid from a jar' },
      { id: 'build_bridge_blocks', text: 'Place 2 blocks side by side' },
      { id: 'peel_banana', text: 'Help peel a banana' },
      { id: 'wash_hands_water', text: 'Rub hands together under running water' },
      { id: 'brush_teeth_try', text: 'Hold toothbrush and attempt to brush' },
      { id: 'put_coins_bank', text: 'Drop coins or tokens into a piggy bank slot' },
      { id: 'wrap_toy', text: 'Try to wrap a small toy in a blanket' },
      { id: 'press_clay_dough', text: 'Poke and squeeze playdough' }
    ]
  },
  '18-20': {
    Athletic: [
      { id: 'run_well_mostly', text: 'Run fairly well without falling' },
      { id: 'stair_climb_hold_two', text: 'Walk up stairs holding rail/hand (2 feet per step)' },
      { id: 'kick_ball_run', text: 'Walk into a ball to kick it' },
      { id: 'jump_off_step', text: 'Jump down from a small step (6 inches)' },
      { id: 'throw_target', text: 'Throw a ball toward a specific target or person' },
      { id: 'walk_back_pull', text: 'Walk backwards pulling a toy' },
      { id: 'climb_furniture_ease', text: 'Climb onto chairs, couches, beds with ease' },
      { id: 'ride_scooter', text: 'Stand and push on a 3-wheel scooter' },
      { id: 'carry_heavy_walk', text: 'Carry a heavy stuffed animal while walking' },
      { id: 'squat_play_long', text: 'Squat and play for a prolonged time without falling' },
      { id: 'dance_rhythm', text: 'Dance with more rhythmic bouncing' },
      { id: 'walk_tiptoe_try', text: 'Try to walk on tiptoes' },
      { id: 'step_over_tall', text: 'Step over a taller obstacle (like a book)' },
      { id: 'push_heavy_box', text: 'Push a heavy box across the floor' },
      { id: 'stair_down_hold_rail', text: 'Walk down stairs holding rail (2 feet per step)' },
      { id: 'balance_beam_wide', text: 'Walk along a wide curb or low border' },
      { id: 'run_stop_fast', text: 'Run and stop suddenly without falling' },
      { id: 'climb_playground_steps', text: 'Climb playground steps independently' },
      { id: 'jump_up_both', text: 'Try to jump up, both feet leaving the floor slightly' },
      { id: 'catch_roll_ball', text: 'Sit and "catch" a rolled ball' }
    ],
    Cognitive: [
      { id: 'name_pictures_many', text: 'Name several pictures in a book' },
      { id: 'know_uses_objects', text: 'Know what ordinary things are for (phone, brush)' },
      { id: 'follow_one_step_no_gest', text: 'Follow 1-step command without gesture' },
      { id: 'twenty_words_plus', text: 'Has an expressive vocabulary of 20+ words' },
      { id: 'two_word_phrase', text: 'Combine 2 words ("more milk", "go out")' },
      { id: 'body_parts_five', text: 'Point to 5-6 different body parts' },
      { id: 'sort_by_shape_piles', text: 'Sort blocks into two piles by shape' },
      { id: 'sing_song_end', text: 'Attempt to sing the end word of a song line' },
      { id: 'imitate_environment_car', text: 'Pretend to drive a car with a toy wheel' },
      { id: 'find_hidden_complex2', text: 'Find toy hidden under 3 layered covers' },
      { id: 'concept_mine', text: 'Understand the concept of "mine"' },
      { id: 'match_sounds_animals', text: 'Match an animal figure to the sound it makes' },
      { id: 'know_animal_names', text: 'Name 3-4 zoo or farm animals' },
      { id: 'complete_sentences_book', text: 'Fill in the blank in a familiar rhyming book' },
      { id: 'puzzle_four_piece', text: 'Complete a 4-piece chunky puzzle' },
      { id: 'understand_hot_avoid', text: 'Understand "hot" and avoid touching' },
      { id: 'sort_trash_can', text: 'Know where the garbage can is and throw things away' },
      { id: 'find_matching_sock', text: 'Find the other matching sock in a pile' },
      { id: 'recognize_logo', text: 'Recognize a familiar logo (like a favorite snack)' },
      { id: 'imitate_words_eager', text: 'Eagerly echo words they hear you say' }
    ],
    Social: [
      { id: 'explore_alone_near', text: 'Explore alone with parent close by' },
      { id: 'temper_tantrum_forceful', text: 'Express frustration / say "No" forcefully' },
      { id: 'simple_pretend_drive', text: 'Simple pretend play (feeding doll, driving)' },
      { id: 'show_shame_guilt', text: 'Look guilty or hide when doing something wrong' },
      { id: 'cling_new_loud', text: 'Cling tightly in a new, loud situation' },
      { id: 'parallel_play_near_kids', text: 'Sit next to another kid playing with similar toys' },
      { id: 'hit_bite_frustrated', text: 'May occasionally hit or bite when frustrated' },
      { id: 'comfort_parent_cry', text: 'Bring parent a toy if parent pretends to cry' },
      { id: 'demand_attention_pull', text: 'Pull on your hand to show you something' },
      { id: 'greet_friends_park', text: 'Say "hi" to familiar children at daycare/park' },
      { id: 'possessive_toys_mine', text: 'Yell "mine!" when another child takes a toy' },
      { id: 'help_dress2_undress', text: 'Actively help undress (pull off pants)' },
      { id: 'wait_turn_short_slide', text: 'Wait briefly for a turn at the slide' },
      { id: 'praise_self_yay', text: 'Say "Yay!" for their own accomplishments' },
      { id: 'routine_rigid_demand', text: 'Demand things be done a certain way (routine)' },
      { id: 'imitate_peers_siblings', text: 'Copy what an older sibling is doing' },
      { id: 'show_humor_goofy', text: 'Try to make you laugh by acting goofy' },
      { id: 'kiss_goodnight_init', text: 'Initiate a kiss goodnight before bed' },
      { id: 'share_with_parent_not_kids', text: 'Readily share toys with an adult, but not kids' },
      { id: 'enjoy_chores_laundry', text: 'Love helping with the laundry or dishwasher' }
    ],
    FineMotor: [
      { id: 'stack_six_tower', text: 'Stack 6 blocks in a tower' },
      { id: 'eat_spoon_well_min', text: 'Eat with a spoon with minimal spilling' },
      { id: 'draw_lines_imitate', text: 'Imitate drawing a vertical or horizontal line' },
      { id: 'use_straw_drink', text: 'Drink effectively from a straw cup' },
      { id: 'turn_pages_single_paper', text: 'Turn paper pages one by one' },
      { id: 'unzip_jacket_open', text: 'Unzip and pull open a jacket' },
      { id: 'peg_board_small_pegs', text: 'Place smaller pegs into a board' },
      { id: 'string_large_beads_few', text: 'String 2-3 large beads' },
      { id: 'open_door_turn_knob', text: 'Turn a knob and open a door' },
      { id: 'build_train_blocks', text: 'Line up 3-4 blocks horizontally as a "train"' },
      { id: 'scissors_snip_try', text: 'Attempt to make a single snip with child scissors' },
      { id: 'playdough_roll_snake', text: 'Roll playdough into a snake' },
      { id: 'peel_wrapper_cheese', text: 'Peel the wrapper off a stick of cheese' },
      { id: 'pour_water_pitcher', text: 'Pour water from a small pitcher to a cup (messy!)' },
      { id: 'put_on_hat_head', text: 'Put a hat on their own head' },
      { id: 'take_apart_duplo_blocks', text: 'Pull apart tight interlocking blocks (Duplos)' },
      { id: 'wash_face_cloth', text: 'Wipe face with a washcloth' },
      { id: 'turn_screws_toy', text: 'Turn a large plastic toy screw' },
      { id: 'place_stickers_paper', text: 'Peel and place stickers on paper' },
      { id: 'fold_paper_half', text: 'Attempt to fold a piece of paper in half' }
    ]
  },
  '21-24': {
    Athletic: [
      { id: 'jump_two_feet_off', text: 'Jump off floor with both feet simultaneously' },
      { id: 'kick_ball_fwd_move', text: 'Kick a ball moving forward' },
      { id: 'throw_overhand_good_dir', text: 'Throw a ball overhand with some direction' },
      { id: 'run_well_avoid', text: 'Run well avoiding obstacles' },
      { id: 'stair_climb_alt_rail', text: 'Walk up stairs alternating feet (with rail)' },
      { id: 'tricycle_pedal', text: 'Sit on tricycle and attempt to pedal (or use feet)' },
      { id: 'walk_tiptoe_good_smooth', text: 'Walk on tiptoes a few steps smoothly' },
      { id: 'balance_one_2s_hold', text: 'Balance on one foot for 2 seconds' },
      { id: 'catch_large_chest', text: 'Catch a large softly thrown ball against chest' },
      { id: 'climb_jungle_gym', text: 'Climb jungle gym equipment independently' },
      { id: 'jump_forward_inches', text: 'Jump forward a few inches' },
      { id: 'somersault_try', text: 'Attempt a forward somersault (with guidance)' },
      { id: 'hang_bar_sec', text: 'Hang from a low bar for a few seconds' },
      { id: 'dodge_kids_run', text: 'Run and dodge other playing children' },
      { id: 'walk_curb_alone', text: 'Walk along a curb without falling off' },
      { id: 'dance_complex_copy', text: 'Copy a simple dance move' },
      { id: 'ride_balance_bike', text: 'Walk/glide on a balance bike' },
      { id: 'squat_jump_high', text: 'Squat down and jump up high' },
      { id: 'creep_fast_bear', text: 'Bear crawl rapidly for fun' },
      { id: 'stair_down_alone_hold', text: 'Walk down stairs alone (2 feet per step)' }
    ],
    Cognitive: [
      { id: 'two_step_shoe', text: 'Follow a 2-step command (Get shoe, bring)' },
      { id: 'sort_colors_well_piles', text: 'Sort primary colors into separate piles' },
      { id: 'name_body_parts_many', text: 'Name 6+ body parts' },
      { id: 'fifty_words_plus', text: 'Uses 50+ words clearly' },
      { id: 'three_word_phrase_want', text: 'Say a 3-word sentence ("I want ball")' },
      { id: 'know_pronouns_mixed', text: 'Use pronouns like I, me, you (sometimes mixed up)' },
      { id: 'concept_big_small_obj', text: 'Understand "big" versus "small"' },
      { id: 'puzzle_six_piece', text: 'Complete a 5-6 piece inset puzzle' },
      { id: 'name_objects_all', text: 'Can name almost all common everyday objects' },
      { id: 'count_two_three', text: 'Count 2 or 3 items ("One, Two!")' },
      { id: 'imitate_routines_complex', text: 'Imitate complex adult routines (making coffee)' },
      { id: 'ask_what_that', text: 'Start asking "What\'s that?" constantly' },
      { id: 'recognize_abc_letters', text: 'Recognize a few letters of the alphabet' },
      { id: 'know_own_age_fingers', text: 'Hold up 2 fingers when asked how old they are' },
      { id: 'sort_shapes_three', text: 'Sort circles, squares, and triangles' },
      { id: 'know_gender_book', text: 'Identify boys vs girls in a book' },
      { id: 'concept_in_on_under', text: 'Understand prepositions (in, on, under)' },
      { id: 'match_picture_obj_perf', text: 'Match a 3D object to a 2D picture perfectly' },
      { id: 'sing_full_song_abc', text: 'Sing phrases of Twinkle Twinkle or ABCs' },
      { id: 'remember_past_yes', text: 'Talk about something that happened yesterday' }
    ],
    Social: [
      { id: 'parallel_play_interact', text: 'Play alongside other children interactively' },
      { id: 'defiant_behavior', text: 'Show defiant behavior (doing what they are told not to)' },
      { id: 'copy_adults_kids', text: 'Copy adults and older children directly' },
      { id: 'fear_imaginary_dark', text: 'Show fear of monsters or the dark' },
      { id: 'pretend_roles_dog', text: 'Pretend to be a dog or a baby' },
      { id: 'play_house_doc', text: 'Engage in simple dramatic play (cooking, doctor)' },
      { id: 'share_sometimes_prompt', text: 'Will share a toy if prompted by an adult' },
      { id: 'independent_do_it', text: 'Insist on "I do it myself!"' },
      { id: 'express_emotions_words', text: 'Say "I mad" or "I happy"' },
      { id: 'comfort_friend_sad', text: 'Offer a toy to a sad peer' },
      { id: 'take_turns_game_ball', text: 'Roll a ball back and forth 5+ times' },
      { id: 'notice_gender_diff', text: 'Notice physical differences between boys/girls' },
      { id: 'greet_peers_name', text: 'Call friends by name at daycare' },
      { id: 'stall_bedtime_excuses', text: 'Invent excuses to delay bedtime' },
      { id: 'protect_sibling_baby', text: 'Show protective behavior toward a younger baby' },
      { id: 'enjoy_routines_strict', text: 'Find comfort in strict daily routines' },
      { id: 'show_off_tricks', text: 'Perform tricks explicitly to get applause' },
      { id: 'wait_patiently_min', text: 'Wait 1-2 minutes for a reward or snack' },
      { id: 'apologize_sorry', text: 'Say "sorry" (even if they don\'t totally grasp it)' },
      { id: 'play_chase_peers_run', text: 'Chase other toddlers around grinning' }
    ],
    FineMotor: [
      { id: 'stack_eight_blocks', text: 'Stack 7-8+ blocks' },
      { id: 'draw_circle_closed', text: 'Attempt to draw a closed circle' },
      { id: 'turn_pages_thin_perf', text: 'Turn paper pages one by one perfectly' },
      { id: 'use_fork_well_spear', text: 'Spear food with a fork easily' },
      { id: 'put_on_shoes_try', text: 'Try putting on own shoes (often on wrong feet)' },
      { id: 'unbutton_large', text: 'Unbutton a large button' },
      { id: 'string_small_bead_lace', text: 'String smaller beads on a lace' },
      { id: 'paint_brush_hold', text: 'Hold a paintbrush and stroke paper' },
      { id: 'build_tower_door_arch', text: 'Build a block structure with an arch/door' },
      { id: 'wash_dry_hands_min', text: 'Wash and dry hands with minimal help' },
      { id: 'pour_pitcher_cup', text: 'Pour milk from a small pitcher to a cup' },
      { id: 'take_off_shirt_loose', text: 'Pull off a loose t-shirt' },
      { id: 'cut_paper_scissors', text: 'Snip paper multiple times with scissors' },
      { id: 'knead_clay_tough', text: 'Knead and squish tough clay or putty' },
      { id: 'use_tools_hammer', text: 'Use a toy hammer to pound pegs' },
      { id: 'twist_doorknob_turn', text: 'Turn a round doorknob to open a door' },
      { id: 'fasten_velcro_strap', text: 'Strap velcro shoes tightly' },
      { id: 'pick_up_pins_beads', text: 'Pick up small items like pins or beads easily' },
      { id: 'zip_jacket_pull', text: 'Pull a zipper up once it is connected' },
      { id: 'draw_faces_lines', text: 'Draw a circle and add lines inside for a "face"' }
    ]
  }
};
